### ISSUE TITLE
Change retromods submodule to https:// instead of git@

### ISSUE THREAD

**Issue by RobLoach** [fr500/invader#1]
Having the submodule checkout with git@git.retromods.org asks for git@git.retromods.org's password.

If you change it to https:// it'll skip auth.

**Comment by andres-asm** [comment]
Hey my first issue! cheers

Oh, right! I will change it ASAP

**Comment by andres-asm** [comment]
Fixed https://github.com/fr500/invader/commit/b4977a637962f6c402dfd8b9773d259a894fb4c6
